---
- name: citus_cluster_manage_db | Check database is in read/write mode
  community.postgresql.postgresql_query:
    query: "SELECT pg_catalog.pg_is_in_recovery()"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    db: "postgres"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  become: yes
  become_user: "postgres"
  register: db_status

- name: citus_cluster_manage_db | Create databases
  community.postgresql.postgresql_db:
    name: "{{ line_item.name }}"
    owner: "{{ line_item.owner | default(pg_owner) }}"
    encoding: "{{ line_item.encoding | default(omit) }}"
    lc_collate: "{{ line_item.lc_collate | default(omit) }}"
    lc_ctype: "{{ line_item.lc_ctype | default(omit) }}"
    template: "{{ line_item.template | default('template0') }}"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    maintenance_db: "postgres"
    state: "{{ line_item.state | default('present') }}"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  become: yes
  become_user: "postgres"
  with_items: "{{ citus_postgres_databases }}"
  loop_control:
    loop_var: line_item
  when:
    - not db_status.query_result[0].pg_is_in_recovery
    - citus_postgres_databases|length > 0