---
- name: citus_cluster_manage_users | Check database is in read/write mode
  community.postgresql.postgresql_query:
    query: "SELECT pg_catalog.pg_is_in_recovery()"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    db: "postgres"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  become: yes
  become_user: "postgres"
  register: db_status

- name: citus_cluster_manage_users | Manage system users
  community.postgresql.postgresql_user:
    name: "{{ line_item.name }}"
    password: "{{ line_item.password | default(omit) }}"
    encrypted: "{{ line_item.encrypted | default(omit) }}"
    conn_limit: "{{ line_item.conn_limit | default(omit) }}"
    expires: "{{ line_item.expires | default(omit) }}"
    priv: "{{ line_item.priv | default(omit) }}"
    role_attr_flags: "{{ line_item.role_attr_flags | default(omit) }}"
    groups: "{{ line_item.groups | default(omit) }}"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    state: "{{ line_item.state | default('present') }}"
    db: "postgres"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  no_log: True
  become: yes
  become_user: "postgres"
  with_items: "{{ citus_postgres_system_users }}"
  loop_control:
    loop_var: line_item
  when:
    - not db_status.query_result[0].pg_is_in_recovery
    - citus_postgres_system_users|length > 0

- name: citus_cluster_manage_users | Manage application users
  community.postgresql.postgresql_user:
    name: "{{ line_item.name }}"
    password: "{{ line_item.password | default(omit) }}"
    encrypted: "{{ line_item.encrypted | default(omit) }}"
    conn_limit: "{{ line_item.conn_limit | default(omit) }}"
    expires: "{{ line_item.expires | default(omit) }}"
    priv: "{{ line_item.priv | default(omit) }}"
    role_attr_flags: "{{ line_item.role_attr_flags | default(omit) }}"
    groups: "{{ line_item.groups | default(omit) }}"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    state: "{{ line_item.state | default('present') }}"
    db: "postgres"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  no_log: True
  become: yes
  become_user: "postgres"
  with_items: "{{ citus_postgres_application_users }}"
  loop_control:
    loop_var: line_item
  when:
    - not db_status.query_result[0].pg_is_in_recovery
    - citus_postgres_application_users|length > 0

- name: citus_cluster_manage_users | Manage change data capture users
  community.postgresql.postgresql_user:
    name: "{{ line_item.name }}"
    password: "{{ line_item.password | default(omit) }}"
    encrypted: "{{ line_item.encrypted | default(omit) }}"
    conn_limit: "{{ line_item.conn_limit | default(omit) }}"
    expires: "{{ line_item.expires | default(omit) }}"
    priv: "{{ line_item.priv | default(omit) }}"
    role_attr_flags: "{{ line_item.role_attr_flags | default(omit) }}"
    groups: "{{ line_item.groups | default(omit) }}"
    port: "{{ citus_postgres_coordinator_conf_params.port | default('5432') }}"
    state: "{{ line_item.state | default('present') }}"
    db: "postgres"
    login_user: "postgres"
    login_unix_socket: "/var/run/postgresql"
  no_log: True
  become: yes
  become_user: "postgres"
  with_items: "{{ citus_postgres_change_data_capture_users_users }}"
  loop_control:
    loop_var: line_item
  when:
    - not db_status.query_result[0].pg_is_in_recovery
    - citus_postgres_change_data_capture_users_users|length > 0