---
scenario:
  default:
    - lint
    - converge
    - verify
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: vm-dev-citus-coordinator-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-coordinator-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-monitor-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-3
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-4
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
  - name: vm-dev-citus-worker-5
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: citus
provisioner:
  name: ansible
  log: true
  ansible_args:
    - --inventory=tests/inventory
    - --skip-tags=update_etc_hosts
  config_options:
    defaults:
      deprecation_warnings: false
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible