---
name: Molecule Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        molecule_distro: ['centos7']

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          path: "${{ github.repository }}"
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ansible==2.10.7 ansible-lint flake8 molecule===3.3.4 molecule-docker
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
  release:
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}